In [1]:
import numpy as np

def matrix_multiplication(A, B):
    """Perform matrix multiplication from scratch."""
    if A.shape[1] != B.shape[0]:
        print("Matrix multiplication is not defined for the given matrices.")
        return None
    
    result = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i, j] += A[i, k] * B[k, j]
    
    return result

In [2]:
# Problem 1: Manually compute matrix multiplication
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [3]:
# Problem 2: Use NumPy functions
result_numpy_matmul = np.matmul(A, B)
result_numpy_dot = np.dot(A, B)

In [4]:
# Problem 3: Compute one element manually
row, col = 0, 0  # First element
manual_element = sum(A[row, k] * B[k, col] for k in range(A.shape[1]))

In [5]:
# Problem 4: Implement full matrix multiplication from scratch
result_scratch = matrix_multiplication(A, B)

In [6]:
# Problem 5: Handle invalid matrices
D = np.array([[-1, 2, 3], [4, -5, 6]])
E = np.array([[-9, 8, 7], [6, -5, 4]])
matrix_multiplication(D, E)  

Matrix multiplication is not defined for the given matrices.


In [8]:
# Problem 6: Compute using transposed matrix
E_transposed = E.T
result_transposed = matrix_multiplication(D, E_transposed)




In [9]:
# Print results
print("NumPy matmul result:\n", result_numpy_matmul)
print("NumPy dot result:\n", result_numpy_dot)
print("Manual calculation of one element (0,0):", manual_element)
print("Scratch implementation result:\n", result_scratch)
print("Result with transposed matrix:\n", result_transposed)

NumPy matmul result:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
NumPy dot result:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Manual calculation of one element (0,0): 6
Scratch implementation result:
 [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
Result with transposed matrix:
 [[ 46.  -4.]
 [-34.  73.]]
