In [1]:
import numpy as np

# Problem 1: Calculating matrix multiplication by hand
# A = [[-1, 2, 3], [4, -5, 6], [7, 8, -9]]
# B = [[0, 2, 1], [0, 2, -8], [2, 9, -1]]

# Manual calculation explanation
def explain_manual_calculation():
    print("Manual calculation of matrix multiplication A × B:")
    print("For a 3×3 matrix result C, we calculate each element C[i,j] as follows:")
    
    A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
    B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
    
    # Calculation and explanation of the first element C[0,0]
    print("\nC[0,0] = A[0,0]*B[0,0] + A[0,1]*B[1,0] + A[0,2]*B[2,0]")
    print(f"C[0,0] = (-1)*(0) + (2)*(0) + (3)*(2) = {-1*0 + 2*0 + 3*2}")
    
    # Calculating and explanation of the first row
    print("\nCalculating the first row of C:")
    for j in range(3):
        calculation = f"C[0,{j}] = "
        result = 0
        for k in range(3):
            if k > 0:
                calculation += " + "
            calculation += f"A[0,{k}]*B[{k},{j}]"
            result += A[0,k] * B[k,j]
        calculation += f" = {result}"
        print(calculation)
    
    # Show the full result matrix
    print("\nFull result matrix C:")
    C = np.zeros((3,3))
    for i in range(3):
        for j in range(3):
            for k in range(3):
                C[i,j] += A[i,k] * B[k,j]
    print(C)


In [2]:
# Problem 2: Calculation using NumPy functions
def numpy_calculation():
    A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
    B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
    
    result_matmul = np.matmul(A, B)
    result_dot = np.dot(A, B)
    result_operator = A @ B
    
    print("\nNumPy matmul result:")
    print(result_matmul)
    print("\nNumPy dot result:")
    print(result_dot)
    print("\nNumPy @ operator result:")
    print(result_operator)
    
    # Verifying all methods give the same result
    print("\nAll methods give the same result:", 
          np.array_equal(result_matmul, result_dot) and np.array_equal(result_dot, result_operator))

In [3]:
# Problem 3: Implementing calculations for a certain element
def calculate_single_element():
    A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
    B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
    
    # Calculate element C[0,0]
    i, j = 0, 0
    element = 0
    for k in range(A.shape[1]):
        element += A[i,k] * B[k,j]
    
    print(f"\nManual calculation of element C[{i},{j}]:")
    print(f"C[{i},{j}] = A[{i},0]*B[0,{j}] + A[{i},1]*B[1,{j}] + A[{i},2]*B[2,{j}]")
    print(f"C[{i},{j}] = {A[i,0]}*{B[0,j]} + {A[i,1]}*{B[1,j]} + {A[i,2]}*{B[2,j]} = {element}")
    
    # Verify with NumPy
    print(f"NumPy result for C[{i},{j}]:", np.matmul(A, B)[i,j])

In [4]:
# Problem 4: Creating a function to perform matrix multiplication
def matrix_multiplication(A, B):
    """Perform matrix multiplication from scratch."""
    
    # Check if matrix multiplication is defined for the given matrices
    if A.shape[1] != B.shape[0]:
        print("Error: Matrix multiplication is not defined for these matrices.")
        print(f"Matrix A has shape {A.shape} and matrix B has shape {B.shape}.")
        print(f"Number of columns in A ({A.shape[1]}) must equal number of rows in B ({B.shape[0]}).")
        return None
    
    # Initialize result matrix with zeros
    result = np.zeros((A.shape[0], B.shape[1]))
    
    # Perform multiplication
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i,j] += A[i,k] * B[k,j]
    
    return result

def scratch_implementation():
    A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
    B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
    
    result = matrix_multiplication(A, B)
    
    print("\nScratch implementation result:")
    print(result)
    
    # Verify result against NumPy
    print("\nDoes scratch implementation match NumPy?", np.array_equal(result, np.matmul(A, B)))


In [5]:
# Problem 4: Creating a function to perform matrix multiplication
def matrix_multiplication(A, B):
    """Perform matrix multiplication from scratch."""
    
    # Check if matrix multiplication is defined for the given matrices
    if A.shape[1] != B.shape[0]:
        print("Error: Matrix multiplication is not defined for these matrices.")
        print(f"Matrix A has shape {A.shape} and matrix B has shape {B.shape}.")
        print(f"Number of columns in A ({A.shape[1]}) must equal number of rows in B ({B.shape[0]}).")
        return None
    
    # Initialize result matrix with zeros
    result = np.zeros((A.shape[0], B.shape[1]))
    
    # Perform multiplication
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i,j] += A[i,k] * B[k,j]
    
    return result

def scratch_implementation():
    A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
    B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
    
    result = matrix_multiplication(A, B)
    
    print("\nScratch implementation result:")
    print(result)
    
    # Verify result against NumPy
    print("\nDoes scratch implementation match NumPy?", np.array_equal(result, np.matmul(A, B)))


In [9]:
# Problem 5: Evaluating inputs that are not defined
def test_invalid_matrices():
    D = np.array([[-1, 2, 3], [4, -5, 6]])
    E = np.array([[-9, 8, 7], [6, -5, 4]])
    
    print("\nTesting invalid matrices:")
    print(f"D shape: {D.shape}, E shape: {E.shape}")
    
    result = matrix_multiplication(D, E)
    print("Result:", result)

In [10]:
# Problem 6: Transposition
def transposition_example():
    D = np.array([[-1, 2, 3], [4, -5, 6]])
    E = np.array([[-9, 8, 7], [6, -5, 4]])
    
    print("\nTransposition example:")
    print("Original matrices:")
    print("D =\n", D)
    print("E =\n", E)
    
    # Transpose E using both methods
    E_transpose_func = np.transpose(E)
    E_transpose_attr = E.T
    
    print("\nTransposed E using np.transpose():")
    print(E_transpose_func)
    print("\nTransposed E using .T attribute:")
    print(E_transpose_attr)
    
    # Check if multiplication is now possible
    print("\nCan multiply D and E^T?", D.shape[1] == E_transpose_attr.shape[0])
    
    if D.shape[1] == E_transpose_attr.shape[0]:
        result = matrix_multiplication(D, E_transpose_attr)
        print("\nResult of D × E^T:")
        print(result)
        
        # Verify with NumPy
        print("\nVerify with NumPy (D @ E.T):")
        print(D @ E.T)

In [11]:
#Executing all functions

In [12]:
explain_manual_calculation()
numpy_calculation()
calculate_single_element()
scratch_implementation()
test_invalid_matrices()
transposition_example()

Manual calculation of matrix multiplication A × B:
For a 3×3 matrix result C, we calculate each element C[i,j] as follows:

C[0,0] = A[0,0]*B[0,0] + A[0,1]*B[1,0] + A[0,2]*B[2,0]
C[0,0] = (-1)*(0) + (2)*(0) + (3)*(2) = 6

Calculating the first row of C:
C[0,0] = A[0,0]*B[0,0] + A[0,1]*B[1,0] + A[0,2]*B[2,0] = 6
C[0,1] = A[0,0]*B[0,1] + A[0,1]*B[1,1] + A[0,2]*B[2,1] = 29
C[0,2] = A[0,0]*B[0,2] + A[0,1]*B[1,2] + A[0,2]*B[2,2] = -20

Full result matrix C:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]

NumPy matmul result:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

NumPy dot result:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

NumPy @ operator result:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

All methods give the same result: True

Manual calculation of element C[0,0]:
C[0,0] = A[0,0]*B[0,0] + A[0,1]*B[1,0] + A[0,2]*B[2,0]
C[0,0] = -1*0 + 2*0 + 3*2 = 6
NumPy result for C[0,0]: 6

Scratch implementation result:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]

Does